
"""
Support for the Hildon widget set, used in touchscreen phones on Nokia's Maemo platform.
For now highly experimental and not regularly tested.
"""

import hildon, describer, simulator, guiusecase, widgetadapter

def addHildonSupport():
    describer.describerClass = Describer
    guiusecase.WidgetAdapter.adapterClass = WidgetAdapter
    Describer.addHildonWidgets()
    simulator.eventTypes += [(hildon.CheckButton , [ simulator.miscevents.ActivateEvent ]),
                             (hildon.AppMenu     , [ AppMenuEvent ])]

class WidgetAdapter(widgetadapter.WidgetAdapter):
    def isAutoGenerated(self, name):
        return widgetadapter.WidgetAdapter.isAutoGenerated(self, name) or name.startswith("Hildon") 

class AppMenuEvent(simulator.baseevents.SignalEvent):
    signalName = "show"
    def generate(self, *args):
        return self.widget.show()

class Describer(describer.Describer):
    @classmethod
    def addHildonWidgets(cls):
        cls.supportedWidgets = [ hildon.CheckButton ] + cls.supportedWidgets

    def getCheckButtonDescription(self, widget):
        return self.getToggleButtonDescription(widget)
    
    def isCheckWidget(self, button):
        return isinstance(button, hildon.CheckButton) or describer.Describer.isCheckWidget(self, button)
